id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: "Needs: Author Feedback \U0001F442"
      - noActivitySince:
          days: 8
      actions:
      - closeIssue
      - addReply:
          reply: This issue was closed automatically as author feedback was indicated as needed, but there has been no activity in over a week. Please feel free to reopen with any available information!
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Resolution-Duplicate
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity in a day. It has been closed for housekeeping purposes.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - hasLabel:
          label: Resolution-Answered
      - noActivitySince:
          days: 1
      actions:
      - closeIssue
      - addReply:
          reply: This issue has been marked as answered and has not had any activity in a day. It has been automatically closed for housekeeping purposes.
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - hasLabel:
          label: "Needs: Repro Info \U0001F914"
      - noActivitySince:
          days: 8
      actions:
      - addReply:
          reply: This issue was closed automatically as repro info was indicated as needed, but there has been no activity in over a week. Please feel free to reopen with any available information!
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - hasLabel:
          label: Resolution-External
      actions:
      - closeIssue
      - addReply:
          reply: This issue has been marked as external. It has been automatically closed for housekeeping purposes.
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - hasLabel:
          label: Resolution-Fixed
      actions:
      - closeIssue
      - addReply:
          reply: This issue has been marked as fixed. It has been automatically closed for housekeeping purposes.
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - hasLabel:
          label: Resolution-Inactive
      actions:
      - addReply:
          reply: This issue has been marked as inactive. It has been automatically closed for housekeeping purposes.
      - closeIssue
    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - hasLabel:
          label: "Needs: Author Feedback \U0001F442"
      - isActivitySender:
          issueAuthor: True
      then:
      - addLabel:
          label: 'Needs: Attention :wave:'
      - removeLabel:
          label: "Needs: Author Feedback \U0001F442"
      description: 
    - if:
      - payloadType: Pull_Request
      then:
      - labelSync:
          pattern: Issue-*
      - labelSync:
          pattern: Area-*
      description: 
    - if:
      - payloadType: Issue_Comment
      - not: isOpen
      - isAction:
          action: Created
      - hasLabel:
          label: "Needs: Author Feedback \U0001F442"
      - isActivitySender:
          issueAuthor: True
      then:
      - reopenIssue
      - removeLabel:
          label: "Needs: Author Feedback \U0001F442"
      - addLabel:
          label: 'Needs: Attention :wave:'
      description: 
    - if:
      - payloadType: Issue_Comment
      then:
      - cleanEmailReply
      description: 
onFailure: 
onSuccess: 
